config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resources :events
  resources :invitations, only: [:edit, :update, :destroy]
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User",
  foreign_key: "creator_id" 
  
  has_many :invitations, foreign_key: "attended_event_id"
  has_many :attendees, through: :invitations, source: :attendee
  scope :past, -> {where("date < :current_date", {current_date: Time.now})}
  scope :future, -> {where("date > :current_date", {current_date: Time.now})}
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  #through table
  belongs_to :attended_event, class_name: "Event", foreign_key: "attended_event_id"
  belongs_to :attendee, class_name: "User", foreign_key: "attendee_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: "creator_id", dependent: :destroy 
  # belongs_to :attended_event, class_name: "Event", foreign_key: "attendee_id"
  has_many :invitations, foreign_key: "attendee_id"
  has_many :attended_events, through: :invitations, source: :attended_event
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    # indexes all events
    @events = Event.all
  end
  def create
    @event = current_user.events.build(event_params)
    if @event.save 
      redirect_to @event
    else
      render 'new'
    end
  end
  def edit 
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end
  def new
    @event = current_user.events.build
  end

  def show
    @event = Event.find(params[:id])
  end
  private 
  
  def event_params 
    params.require(:event).permit(:name, :location, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :find_event, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  def edit 
    # "/invitations/:id/edit"

  end

  def update
    #has event because of edit
    #adds current user to event attendes
    @event.attendees << current_user
    redirect_to controller: "events", action: :index
  end
  def destroy
    #has event because of edit
    #adds current user to event attendes
    @event.attendees.delete(current_user)
    redirect_to controller: "events", action: :index
  end

  # identifies event
  def find_event
    @event = Event.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
 <%= render "shared/navbar" %>
<%= form_with model: @event do |event|%>
  <%= event.label :name, "Name: " %>
  <%= event.text_field :name%>
  <%= event.label :name, "Location: " %>
  <%= event.text_field :location%>
  <%= event.label :date, "Date: " %>
  <%= event.date_field :date %>
  <%= event.submit "Submit" %>
<% end %>
<% if user_signed_in? %>
 <%= button_to "Delete",  event_path(params[:id]), method: :delete%>
<% end%>

app/views/events/index.html.erb
 <%= render "shared/navbar" %>
<h1>Index Events</h1>
<% @events.each do |event|%>
  <h2><%= event.name %></h3>
  <h3><%= event.location%></h3>
  <h3><%= event.date %></h3>
  <h3><%= link_to "Edit", edit_event_path(event)%></h3>
  <h3><%= link_to "RSPV", edit_invitation_path(event)%></h3>
<% end %>

app/views/events/new.html.erb
<%= form_with model: @event do |event|%>
  <%= event.label :name, "Name: " %>
  <%= event.text_field :name%>
  <%= event.label :name, "Location: " %>
  <%= event.text_field :location%>
  <%= event.label :date, "Date: " %>
  <%= event.date_field :date %>
  <%= event.submit "Submit" %>
<% end %>

app/views/events/show.html.erb
 <%= render "shared/navbar" %>
<h1>Event: <%= @event.name %></h1>
<p>Location: <%= @event.location%> </p>
<h3>Date: <%= @event.date %></h3>
<h1>Attendees</h1>
<% @event.attendees.each do |attendee|%>
  <h2>Email: <%= attendee.email %></h3>
  <h3>User Id: <%= attendee.id%></h3>
<% end %>

app/views/invitations/edit.html.erb
 <%= render "shared/navbar" %>
<h1>Invitations</h1>
<% if @event.attendees.include?(current_user)%>
  <%= button_to "Leave Event", invitation_path, method: :delete %>
<% else %>
  <%= button_to "Join Event", invitation_path, method: :put %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<ul>
  <li>Navbar</li>
  <li><%= link_to "Start an Event", new_event_path %></li>
  <li> <%= link_to "All Events", events_path %></li>
  <% if user_signed_in? %>
    <li><%= link_to "View User Events", user_path(current_user)%></li>
    <%= button_to "logout", destroy_user_session_path, method: :delete  %>
  <% else %>
    <%= button_to "login", new_user_session_path, method: :new  %>
  <% end %>
</ul>

app/views/users/show.html.erb
 <%= render "shared/navbar" %>
<h1>User Created Events: </h1>
<% @user.events.each do |event| %>
  <h2><%= event.name%></h3>
  <h3><%= event.location%></h3>
  <h3><%= event.date %></h3>
<%end%>
<h2>Future Attended Events</h2>
<% @user.attended_events.future.each do |event|%>
  <h2><%= event.name%></h3>
  <h3><%= event.location%></h3>
  <h3><%= event.date %></h3>
<% end %>
<h2>Past Attended Events</h2>
<% @user.attended_events.past.each do |event|%>
  <h2><%= event.name%></h3>
  <h3><%= event.location%></h3>
  <h3><%= event.date %></h3>
<% end %>